language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_deploy: npm i now --no-save
deploy:
  - provider: script
    script: now --t $NOW_TOKEN --public && now alias --t $NOW_TOKEN --public
    skip_cleanup: true
    on:
      master: true
