language: node
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_deploy: npm install now --no-save
deploy:
  script: now --token $NOW_TOKEN --public
  skip_cleanup: true
  on:
    master: true
